specVersion: 1.0.0
name: magick
version: 0.0.2
runner:
  node:
    name: '@subql/node'
    version: 1.5.1
  query:
    name: '@subql/query'
    version: 1.3.0
description: None
repository: ''
schema:
  file: ./schema.graphql
network:
  chainId: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  endpoint: 'wss://kusama.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/dictionary-kusama'
dataSources:
  - kind: substrate/Runtime
    filter:
      specName: kusama
    startBlock: 4892957
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batch
            success: true
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
            module: system
            method: remark
            success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batch
            success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
            module: system
            method: remark
            success: true
  - kind: substrate/Runtime
    filter:
      specName: westend
    startBlock: 7161214
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batch
            success: true
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
            module: system
            method: remark
            success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batch
            success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
            module: system
            method: remark
            success: true
